name: Build Busybox

on:
  workflow_dispatch:
  watch:
    types: [started]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: Build
        run: |
          export RUN_ID="${{ github.run_id }}"
          export TOKEN="${{ secrets.TG_TOKEN }}"
          export CHAT_ID="${{ secrets.CHAT_ID }}"
          [[ ! -x "scripts/build.sh" ]] && chmod +x scripts/build.sh
          scripts/build.sh