name: Build Busybox

on:
  workflow_dispatch:
  watch:
    types: [started]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          export RUN_ID="${{ github.run_id }}"
          export TOKEN="${{ secrets.TG_TOKEN }}"
          export CHAT_ID="${{ secrets.CHAT_ID }}"
          [[ ! -x "script/build.sh" ]] && chmod +x script/build.sh
          script/build.sh
